name: crypto_news_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Equatable class allows us to compare two object for equality
  equatable: ^2.0.3
  # Firebase packages
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  flutter_bloc: ^7.0.1
  # To access Google Sign-In
  google_sign_in: ^5.4.0
  # To make HTTP requests.
  http: ^0.13.4
  # To launch url
  url_launcher: ^6.1.5
  # used to format time
  timeago: ^3.2.2
  # To add google sign in button
  flutter_signin_button: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg




